name: "ui_palette_example"
environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  equatable: ^1.2.6
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  url_launcher: ^5.7.10

  # Flutter deps
  flutter:
    sdk: flutter

  # Local deps
  app_utils:
    git: https://github.com/AnimeDart/dart-utils

  # Local deps
  ui_palette:
    path: ..

dev_dependencies:
  effective_dart: ^1.0.0
  test: ^1.15.7

flutter:
  uses-material-design: true

  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans-Bold.ttf
        - asset: assets/fonts/JosefinSans-Italic.ttf
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 700
    - family: New Tegomin
      fonts:
        - asset: assets/fonts/NewTegomin-Regular.ttf
          weight: 400
    - family: Interstate Bold
      fonts:
        - asset: assets/fonts/Interstate-Bold.otf
          weight: 700
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
        - asset: assets/fonts/Comfortaa-Light.ttf
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 700
